const guides = {
  ice_maker: {
    title: 'Ice Maker Assembly Replacement',
    tools_needed: ['Phillips head screwdriver', 'Putty knife (optional)'],
    estimated_time: '15-30 minutes',
    difficulty: 'Easy',
    safety: 'Unplug the refrigerator before beginning. Turn off the ice maker water supply.',
    steps: [
      'Unplug the refrigerator from the electrical outlet and turn off the water supply line.',
      'Open the freezer door and remove the ice bucket from beneath the ice maker.',
      'Locate the ice maker assembly mounted to the left wall inside the freezer compartment.',
      'Press the release tab on the wiring harness connector and unplug it from the ice maker.',
      'Using a Phillips screwdriver, remove the 3 mounting screws securing the ice maker to the freezer wall.',
      'Slide the ice maker assembly to the right and lift it away from the mounting studs.',
      'Align the new ice maker assembly with the mounting holes on the freezer wall.',
      'Slide it onto the mounting studs and press it flush against the wall.',
      'Reinstall the 3 mounting screws snugly — do not overtighten.',
      'Reconnect the wiring harness connector until you hear or feel a click.',
      'Replace the ice bucket in its original position.',
      'Turn the water supply back on and plug in the refrigerator.',
      'Allow 24 hours for the ice maker to begin producing ice. Discard the first 1-2 batches.',
    ],
    tips: [
      'If the new ice maker does not produce ice after 24 hours, press the test button (usually a small button on the side of the module).',
      'Make sure the wire shutoff arm is in the down (on) position.',
      'Verify water pressure is between 30-120 PSI for proper fill.',
    ],
  },

  water_filter: {
    title: 'Refrigerator Water Filter Replacement',
    tools_needed: ['No tools required'],
    estimated_time: '5 minutes',
    difficulty: 'Easy',
    safety: 'No power disconnection needed. Have a towel ready for minor drips.',
    steps: [
      'Locate the water filter compartment — usually in the upper-right interior of the fresh food section.',
      'Push in the filter button or tab to release the old filter.',
      'Pull the old filter straight out and discard it.',
      'Remove the protective caps from the new filter ends.',
      'Align the new filter with the filter housing (look for the alignment arrow).',
      'Push the new filter firmly into the housing until it clicks into place.',
      'Flush the system: run approximately 4 gallons (about 3-4 minutes) of water through the dispenser.',
      'Discard the flushed water — it may appear cloudy initially due to air in the system.',
      'Press and hold the filter status light reset button for 3 seconds to reset the indicator.',
    ],
    tips: [
      'Replace the water filter every 6 months or 200 gallons for best performance.',
      'If water flow is very slow after installation, make sure the filter is fully seated.',
      'Running a filter past its expiration reduces filtration effectiveness.',
    ],
  },

  door_gasket_fridge: {
    title: 'Refrigerator Door Gasket Replacement',
    tools_needed: ['Putty knife or flat head screwdriver', 'Hair dryer (optional)', 'Mild soap and water'],
    estimated_time: '30-60 minutes',
    difficulty: 'Moderate',
    safety: 'Keep the refrigerator running during this repair — it goes quickly. Work on one section at a time.',
    steps: [
      'Open the refrigerator door fully and clean the door liner groove where the gasket seats.',
      'Starting at a top corner, use a putty knife to pry the gasket lip out of the door liner retainer groove.',
      'Work around the door, pulling the gasket free from the groove. Note how the lip wraps into the channel.',
      'If the gasket has screws, remove the retainer screws with a Phillips screwdriver before pulling the gasket.',
      'Soak the new gasket in warm water for 10-15 minutes to make it more pliable — or use a hair dryer on low.',
      'Starting at a top corner, push the inner lip of the new gasket firmly into the door liner groove.',
      'Work your way around the door, pressing the gasket lip into the groove every few inches.',
      'Ensure the gasket is evenly seated with no twisted or lifted sections.',
      'Close the door and check the seal on all four sides using a dollar bill: slide it into the closed door — you should feel resistance when pulling it out.',
      'If any sections are loose, warm them with a hair dryer and press back in.',
    ],
    tips: [
      'The dollar bill test: if the bill slides out too easily, the seal is inadequate in that area.',
      'A poor seal will cause condensation, frost buildup, and the compressor running constantly.',
      'Allow the new gasket 24 hours to fully conform to the door shape.',
    ],
  },

  water_inlet_valve: {
    title: 'Refrigerator Water Inlet Valve Replacement',
    tools_needed: ['Phillips and flathead screwdrivers', 'Adjustable wrench or pliers', 'Bucket and towels', 'Nut driver set'],
    estimated_time: '20-40 minutes',
    difficulty: 'Moderate',
    safety: 'Unplug the refrigerator and shut off the water supply before starting. Have towels ready.',
    steps: [
      'Turn off the water supply valve (usually under the sink or behind the refrigerator).',
      'Unplug the refrigerator from the wall outlet.',
      'Pull the refrigerator away from the wall to access the back.',
      'Locate the water inlet valve — it\'s on the lower back of the refrigerator where the water supply line connects.',
      'Place a towel and bucket under the valve to catch residual water.',
      'Unscrew the water supply line from the valve using an adjustable wrench (turn counterclockwise).',
      'Disconnect the 1/4" tubing lines going from the valve to the ice maker and water dispenser (press the collar and pull).',
      'Unplug the wire harness connectors from each solenoid on the valve.',
      'Remove the mounting screws securing the valve bracket to the refrigerator cabinet.',
      'Slide the old valve out.',
      'Mount the new valve using the original screws and bracket position.',
      'Reconnect all wire harness connectors — they are keyed and will only fit one way.',
      'Reconnect the 1/4" tubing by pushing firmly until seated.',
      'Reconnect the water supply line and tighten snugly (don\'t overtighten).',
      'Turn the water supply back on and check all connections for leaks.',
      'Plug in the refrigerator and test the water dispenser and ice maker.',
    ],
    tips: [
      'Take photos before disconnecting anything to reference during reassembly.',
      'Use thread seal tape on the supply line threads to prevent leaks.',
    ],
  },

  door_latch: {
    title: 'Dishwasher Door Latch Replacement',
    tools_needed: ['Phillips head screwdriver', 'Torx T20 screwdriver (some models)'],
    estimated_time: '15-25 minutes',
    difficulty: 'Easy',
    safety: 'Disconnect the dishwasher from power before starting.',
    steps: [
      'Turn off power to the dishwasher at the circuit breaker or unplug it.',
      'Open the dishwasher door fully.',
      'Remove the inner door panel screws around the perimeter of the door (usually 6-8 Phillips screws along the sides and bottom).',
      'Carefully separate the inner door panel from the outer door panel — they are connected by wire harnesses.',
      'Locate the door latch assembly at the top center of the inner door panel.',
      'Disconnect the wire harness connector from the door latch (press the release tab and pull).',
      'Remove the mounting screws holding the latch assembly (usually 2-3 screws).',
      'Note the position of the latch strike on the tub opening before removing it.',
      'Remove the latch strike from the tub top rail (usually 2 screws).',
      'Install the new latch strike in the same position as the old one.',
      'Mount the new door latch assembly with the original screws.',
      'Reconnect the wire harness connector.',
      'Carefully realign the inner door panel with the outer panel, making sure all wires are tucked.',
      'Reinstall all door panel screws evenly.',
      'Restore power and test: close the door and check that the latch engages and the dishwasher starts.',
    ],
    tips: [
      'If the dishwasher still won\'t start after latch replacement, check the door switch continuity with a multimeter.',
      'Ensure the strike and latch align properly — adjustment may require slightly loosening the strike screws.',
    ],
  },

  drain_pump: {
    title: 'Dishwasher Drain Pump Replacement',
    tools_needed: ['Phillips head screwdriver', 'Flat head screwdriver', 'Pliers', 'Towels and bucket'],
    estimated_time: '30-50 minutes',
    difficulty: 'Moderate',
    safety: 'Turn off power and water supply. Have towels ready — residual water will drain.',
    steps: [
      'Turn off the dishwasher circuit breaker and shut off the water supply.',
      'Remove the lower dish rack.',
      'Unscrew and lift out the lower spray arm (turn counterclockwise or lift straight up depending on model).',
      'Remove the filter assembly: twist the cylindrical filter counterclockwise and lift out, then lift out the flat filter screen.',
      'You will now see the drain pump cover at the bottom of the tub. Remove the cover screws.',
      'Tilt the dishwasher back slightly or lay it on its back to access the bottom panel (have a helper or use blocks).',
      'Remove the bottom access panel screws and take off the panel.',
      'Locate the drain pump on the bottom left of the tub. You\'ll see the drain hose and wire connector.',
      'Place towels and a bucket — remaining water will flow out.',
      'Disconnect the drain hose clamp and pull the hose off the pump outlet.',
      'Unplug the wire harness connector from the pump motor.',
      'Rotate the pump counterclockwise (about 1/4 turn) to unlock it from the tub, then pull it down.',
      'Insert the new pump and rotate clockwise to lock.',
      'Reconnect the wire harness and drain hose (secure the clamp).',
      'Reinstall the bottom panel, filter assembly, and spray arm.',
      'Restore power and run a short cycle to test drainage.',
    ],
    tips: [
      'Before replacing the drain pump, check for blockages in the filter and drain hose — a clog is often the cause.',
      'Running the garbage disposal before a wash cycle can help prevent drain clogs.',
    ],
  },

  spray_arm: {
    title: 'Dishwasher Spray Arm Replacement',
    tools_needed: ['No tools typically required (snap-fit design)'],
    estimated_time: '5-10 minutes',
    difficulty: 'Easy',
    safety: 'No power disconnection needed, but good practice to turn it off.',
    steps: [
      'Remove the dish rack from the affected area (upper or lower).',
      'For the lower spray arm: grasp the arm and turn the center hub counterclockwise to unscrew it, then lift the arm off. If it snaps on, push down while rotating.',
      'For the upper spray arm: unscrew the retaining nut on the underside of the upper rack (turn counterclockwise), then lift off the arm.',
      'Before installing the new spray arm, clean the water feed holes and the inlet port with a toothpick if clogged.',
      'Align the new spray arm over the inlet hub.',
      'For lower arm: press down and rotate clockwise until it locks and spins freely.',
      'For upper arm: push onto the hub and hand-tighten the retaining nut clockwise.',
      'Confirm the arm spins freely by hand — it should rotate 360° without obstruction.',
      'Replace the dish rack and run a rinse cycle to verify water sprays properly.',
    ],
    tips: [
      'Periodically clean spray arm holes with a toothpick to prevent clogging from mineral deposits.',
      'If spray arms were just clogged (not broken), soak in white vinegar for 30 minutes and use a toothpick to clear holes.',
    ],
  },

  heating_element: {
    title: 'Dishwasher Heating Element Replacement',
    tools_needed: ['Phillips head screwdriver', 'Nut driver (1/4" or 5/16")', 'Needle-nose pliers'],
    estimated_time: '25-40 minutes',
    difficulty: 'Moderate',
    safety: 'Always disconnect power before working on a heating element.',
    steps: [
      'Turn off power at the circuit breaker.',
      'Remove the lower dish rack and bottom spray arm.',
      'Remove the filter assembly.',
      'Note the routing of the heating element\'s terminal ends through the tub floor.',
      'Remove the bottom access panel (tip the dishwasher back or slide it out first).',
      'Locate the heating element terminals protruding through the bottom of the tub.',
      'Disconnect the wire connectors from both terminals (use needle-nose pliers if tight).',
      'Inside the tub, use a nut driver to remove the locking nuts on each terminal post.',
      'Lift the old heating element out of the tub floor.',
      'Insert the new element, feeding the terminal posts through the tub floor holes.',
      'Thread the locking nuts onto the terminals and tighten firmly.',
      'Reconnect the wire connectors to both terminals on the underside.',
      'Reinstall the access panel, filter, and spray arm.',
      'Run a normal wash cycle to verify heating and drying work correctly.',
    ],
    tips: [
      'Test the old element with a multimeter: set to ohms, touch probes to terminals. Reading should be 15-30 ohms. Open circuit (infinity) = element is burned out.',
    ],
  },

  evaporator_fan: {
    title: 'Freezer Evaporator Fan Motor Replacement',
    tools_needed: ['Phillips head screwdriver', '¼" nut driver', 'Putty knife'],
    estimated_time: '30-45 minutes',
    difficulty: 'Moderate',
    safety: 'Unplug the refrigerator first. The freezer will warm — work quickly.',
    steps: [
      'Unplug the refrigerator from the wall.',
      'Remove all food and shelves from the freezer compartment.',
      'Remove the back panel in the freezer — usually held by 4-6 screws. Use a putty knife to pop off any plastic caps covering screws.',
      'You may encounter ice — use a hair dryer on low to carefully melt it. Do not use anything sharp.',
      'Locate the evaporator fan motor assembly behind the back panel.',
      'Disconnect the wire harness from the fan motor.',
      'Remove the mounting screws holding the fan bracket to the evaporator.',
      'Note the fan blade orientation before removing it — the blade must face the same direction on the new motor.',
      'Pull the fan blade off the motor shaft (it may be press-fit or have a clip).',
      'Unmount the motor from its bracket by removing retaining screws or clips.',
      'Mount the new motor to the bracket in the same orientation.',
      'Reinstall the fan blade — ensure it spins freely without hitting the shroud.',
      'Reconnect the wire harness.',
      'Reinstall the back panel with all screws.',
      'Plug in the refrigerator and verify the fan runs and both compartments cool properly.',
    ],
    tips: [
      'If the freezer is cold but the refrigerator compartment is warm, the evaporator fan is the most common cause.',
      'You can test the fan by pressing the door switch (the button inside the door frame) while the door is open — the fan should run.',
    ],
  },
};

function getInstallationGuide(part_number, part_type) {
  const guide = guides[part_type] || null;

  if (!guide) {
    return {
      found: false,
      message: `We don't have a specific installation guide for this part type. Visit PartSelect.com and search for part ${part_number} to find video instructions.`,
    };
  }

  return {
    found: true,
    part_number,
    ...guide,
  };
}

module.exports = { getInstallationGuide };
